"""Second-1

Revision ID: 474d2bd6d178
Revises: e879dfa60035
Create Date: 2022-06-15 11:26:34.510737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474d2bd6d178'
down_revision = 'e879dfa60035'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
