"""Third-1

Revision ID: aefadff5d407
Revises: 474d2bd6d178
Create Date: 2022-06-15 17:21:10.717306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefadff5d407'
down_revision = '474d2bd6d178'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
