"""Third-1

Revision ID: e0ad265d016e
Revises: aefadff5d407
Create Date: 2022-06-15 17:29:49.836257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0ad265d016e'
down_revision = 'aefadff5d407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_shipping_info', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('users_shipping_info', sa.Column('phone_no', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_shipping_info', 'phone_no')
    op.drop_column('users_shipping_info', 'name')
    # ### end Alembic commands ###
