"""Second

Revision ID: e879dfa60035
Revises: 5f768d55bb0b
Create Date: 2022-06-15 11:19:11.221712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e879dfa60035'
down_revision = '5f768d55bb0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reset_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('expired_in', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_reset_codes_id'), 'reset_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_codes_id'), table_name='reset_codes')
    op.drop_table('reset_codes')
    # ### end Alembic commands ###
