"""Fourth-Update CartTable

Revision ID: f8afdc9d4d59
Revises: 2c5223d9ee48
Create Date: 2022-06-20 11:18:41.665372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8afdc9d4d59'
down_revision = '2c5223d9ee48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_cart', sa.Column('total', sa.Float(), nullable=False))
    op.drop_column('my_cart', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_cart', sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('my_cart', 'total')
    # ### end Alembic commands ###
